/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseGroupMemberRespDto } from '../../models/page-response-group-member-resp-dto';

export interface GetGroupMembers$Params {
  groupId: number;
  page?: number;
  size?: number;
}

export function getGroupMembers(http: HttpClient, rootUrl: string, params: GetGroupMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGroupMemberRespDto>> {
  const rb = new RequestBuilder(rootUrl, getGroupMembers.PATH, 'get');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseGroupMemberRespDto>;
    })
  );
}

getGroupMembers.PATH = '/users/group/members/{groupId}';
