/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseGroupMessageDto } from '../../models/page-response-group-message-dto';

export interface LoadGroupDiscussion$Params {
  page?: number;
  size?: number;
  groupId: number;
}

export function loadGroupDiscussion(http: HttpClient, rootUrl: string, params: LoadGroupDiscussion$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGroupMessageDto>> {
  const rb = new RequestBuilder(rootUrl, loadGroupDiscussion.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.path('groupId', params.groupId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseGroupMessageDto>;
    })
  );
}

loadGroupDiscussion.PATH = '/users/conversation/group/{groupId}';
