/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserRespDto } from '../../models/page-response-user-resp-dto';

export interface ReadExcludedFriends$Params {
  grpId: number;
  page?: number;
  size?: number;
}

export function readExcludedFriends(http: HttpClient, rootUrl: string, params: ReadExcludedFriends$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserRespDto>> {
  const rb = new RequestBuilder(rootUrl, readExcludedFriends.PATH, 'get');
  if (params) {
    rb.path('grpId', params.grpId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserRespDto>;
    })
  );
}

readExcludedFriends.PATH = '/users/friends/excluded-grp/{grpId}';
