/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FriendRequestRespDto {
  accepted?: boolean;
  answered?: boolean;
  id?: number;
  sender?: string;
  sentAt?: string;
}
