/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupMessageDto {
  content?: string;
  groupId?: number;
  senderId?: number;
  senderName?: string;
  sentAt?: string;
  userKicked?: boolean;
}
