/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupRespDto {
  createdAt?: string;
  creator?: string;
  id?: number;
  members?: number;
  name?: string;
}
