/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupMemberRespDto {
  admin?: boolean;
  id?: number;
  joinedAt?: string;
  member?: string;
  status?: 'ADMIN' | 'MEMBER';
}
