/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GroupRespDto } from '../models/group-resp-dto';
export interface PageResponseGroupRespDto {
  content?: Array<GroupRespDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
