/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRespDto {
  belongsToGroup?: boolean;
  firstname?: string;
  friend?: boolean;
  id?: number;
  joined?: string;
  lastname?: string;
}
