spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/dev_database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: yassine
    password: yassine
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


application:
  security:
    jwt:
      jwtExpiration: 864000000
      secret-key: NiZDGe0bmR+kP9rKOuifGkCdoId16jBre0lEPmsjHbo=

  front:
    urls:
      activation: http://localhost:4200/activate-account
      recovery: http://localhost:4200/recover-password
